name: Python Examples

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - "python/**"
      - ".github/workflows/*python*"
  push:
    branches:
      - main
    paths:
      - "python/**"
      - ".github/workflows/*python*"

jobs:
  test_python:
    name: Build Python samples
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, '3.10' ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Build Python Demo
        run: |
          pip install -r requirements.txt
          python ./oberon-example/demo.py
          python ./oberon-example/demo_blinding.py
        shell: pwsh
        working-directory: ./python
